//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vacation.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacations
    {
        public int ID { get; set; }
        public System.DateTime Submission_Date { get; set; }
        public string Employee_Name { get; set; }
        public string Title { get; set; }
        public int Department_id { get; set; }
        public System.DateTime Date_From { get; set; }
        public System.DateTime Date_To { get; set; }
        public System.DateTime Returning { get; set; }
        public string Notes { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
